package com.excudo.mcp;

import com.google.gson.JsonElement;
import com.google.gson.JsonObject;

/**
 * JSON-RPC 2.0 frame builders shared by the MCP protocol handler and
 * every transport. Keeps the wire format in one place so parse-error
 * frames (generated by transports before any handler sees the bytes)
 * and result/error frames (generated by the handler) stay byte-identical.
 */
public final class JsonRpcFrames {

    public static final int PARSE_ERROR = -32700;
    public static final int INVALID_REQUEST = -32600;
    public static final int METHOD_NOT_FOUND = -32601;
    public static final int INVALID_PARAMS = -32602;
    public static final int INTERNAL_ERROR = -32603;

    private JsonRpcFrames() {}

    public static JsonObject result(JsonElement id, JsonObject result) {
        JsonObject response = new JsonObject();
        response.addProperty("jsonrpc", "2.0");
        if (id != null) response.add("id", id);
        response.add("result", result);
        return response;
    }

    public static JsonObject error(JsonElement id, int code, String message) {
        JsonObject response = new JsonObject();
        response.addProperty("jsonrpc", "2.0");
        if (id != null) response.add("id", id);

        JsonObject err = new JsonObject();
        err.addProperty("code", code);
        err.addProperty("message", message);
        response.add("error", err);

        return response;
    }
}
