package com.excudo.core.commands;

import com.excudo.core.llm.LLMRequestBridge;
import org.junit.Test;
import static org.junit.Assert.*;

import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * Unit tests for RequestSchema class and auto-generated LLM schema.
 */
public class RequestSchemaTest {

    @Test
    public void testSchemaConstants() {
        assertEquals("Schema version should be 1.0", "1.0", RequestSchema.SCHEMA_VERSION);
    }

    @Test
    public void testAutoGeneratedSchema() {
        String toolsSchema = LLMRequestBridge.generateLLMToolsSchema();
        assertNotNull("Auto-generated tools schema should not be null", toolsSchema);
        assertTrue("Should be a JSON array", toolsSchema.startsWith("["));
        assertTrue("Should contain create command", toolsSchema.contains("\"create\""));
        assertTrue("Should contain content-edit command", toolsSchema.contains("\"content-edit\""));
        assertTrue("Should contain add-animation command", toolsSchema.contains("\"add-animation\""));
    }

    @Test
    public void testAutoGeneratedCommandReference() {
        String ref = LLMRequestBridge.generateLLMCommandReference();
        assertNotNull("Command reference should not be null", ref);
        assertTrue("Should contain COMMANDS header", ref.contains("COMMANDS:"));
        assertTrue("Should contain create", ref.contains("create"));
        assertTrue("Should contain content-edit", ref.contains("content-edit"));
        assertTrue("Should contain add-shape", ref.contains("add-shape"));
    }

    @Test
    public void testLLMRequestClass() {
        RequestSchema.RequestMetadata metadata = new RequestSchema.RequestMetadata(0.95, "Test reasoning", Arrays.asList("warning1"), true);
        RequestSchema.ActionRequest operation = new RequestSchema.ActionRequest("slide-creation", new HashMap<>(), "Test operation", 1);
        List<RequestSchema.ActionRequest> operations = Arrays.asList(operation);

        RequestSchema.LLMRequest request = new RequestSchema.LLMRequest("1.0", operations, metadata);

        assertEquals("Schema version should be set", "1.0", request.getSchemaVersion());
        assertEquals("Operations should be set", operations, request.getActions());
        assertEquals("Metadata should be set", metadata, request.getMetadata());
    }

    @Test
    public void testOperationRequestClass() {
        Map<String, Object> parameters = new HashMap<>();
        parameters.put("position", 1);
        parameters.put("title", "Test Slide");

        RequestSchema.ActionRequest operation = new RequestSchema.ActionRequest(
            "slide-creation", parameters, "Create a test slide", 1
        );

        assertEquals("Type should be set", "slide-creation", operation.getType());
        assertEquals("Parameters should be set", parameters, operation.getParameters());
        assertEquals("Description should be set", "Create a test slide", operation.getDescription());
        assertEquals("Priority should be set", Integer.valueOf(1), operation.getPriority());
    }

    @Test
    public void testRequestMetadataClass() {
        List<String> warnings = Arrays.asList("Warning 1", "Warning 2");
        RequestSchema.RequestMetadata metadata = new RequestSchema.RequestMetadata(0.85, "Test reasoning", warnings, false);

        assertEquals("Confidence should be set", Double.valueOf(0.85), metadata.getConfidence());
        assertEquals("Reasoning should be set", "Test reasoning", metadata.getReasoning());
        assertEquals("Warnings should be set", warnings, metadata.getWarnings());
        assertEquals("Context used should be set", Boolean.FALSE, metadata.getContextUsed());
    }

    @Test
    public void testDefaultConstructors() {
        RequestSchema.LLMRequest request = new RequestSchema.LLMRequest();
        assertNotNull("LLMRequest default constructor should work", request);

        RequestSchema.ActionRequest operation = new RequestSchema.ActionRequest();
        assertNotNull("OperationRequest default constructor should work", operation);

        RequestSchema.RequestMetadata metadata = new RequestSchema.RequestMetadata();
        assertNotNull("RequestMetadata default constructor should work", metadata);
    }

    @Test
    public void testSettersAndGetters() {
        RequestSchema.LLMRequest request = new RequestSchema.LLMRequest();
        request.setSchemaVersion("1.0");
        assertEquals("Setter should work for schema version", "1.0", request.getSchemaVersion());

        RequestSchema.ActionRequest operation = new RequestSchema.ActionRequest();
        operation.setType("test-type");
        assertEquals("Setter should work for type", "test-type", operation.getType());

        RequestSchema.RequestMetadata metadata = new RequestSchema.RequestMetadata();
        metadata.setConfidence(0.75);
        assertEquals("Setter should work for confidence", Double.valueOf(0.75), metadata.getConfidence());
    }
}
